config/routes.rb
LabOverflow::Application.routes.draw do

  get "search/index"

  devise_for :users
  resources :questions  
  match 'search' => 'search#index', :as => :search

  root :to => "home#index"
    
  resources :questions do
    member do
      get 'accept';
    end
    resources :answers 
  end
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :text
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :title, :text, :user
  has_many :answers  
  belongs_to :user
  has_one :answer, :class_name => "Answer"
  attr_accessor :is_edditable
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
  has_many :questions
  has_many :answers  
  
  def gravatar    
    hash = Digest::MD5.hexdigest(self.email)
    "http://www.gravatar.com/avatar/#{hash}?s=40"
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  respond_to :html, :json
  before_filter :auth, :only => :create
  
  def new
    @answer = Answer.new
    respond_with @answer
  end 
  
  def create
    @question = Question.find(params[:question_id])
    
    @new_answer = Answer.new(params[:answer])
    @new_answer.question = @question
    @new_answer.user = current_user
    
    respond_with @new_answer do |f|
      if @new_answer.save
        f.html { redirect_to question_path(@question), :notice => "Success" }
      else
        f.html { redirect_to question_path(@question), :alert => "Error" }
      end
    end      
  end  
  
  private
  def auth
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  
  def index
    @questions = Question.all
    respond_with @questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  respond_to :html, :json
  before_filter :auth, :only => [:new, :create, :edit]

  def show
    @question = Question.find(params[:id])
    
    if current_user && current_user.id == @question.user.id
        @question.is_edditable = true
    end
    
    respond_with @question
  end    
  
  def new
    @question = Question.new
    respond_with @question
  end
  
  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    respond_with @question do |format|
      if @question.save
        format.html { redirect_to root_url, :notice => "Success" }
      end
    end    
  end
  
  def update
    @question = Question.find(params[:id])
    
    respond_with @question  do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to root_url, :notice => "Success" }
      else
        format.html{ redirect_to new_question_path  }
      end
    end
  end
  
  def edit
    @question = Question.find(params[:id])
    if current_user && current_user.id == @question.user.id
        @question.is_edditable = true
    end
    respond_with @question
  end
  
  def accept
    @question = Question.find(params[:id])
    
    if(@question.user == current_user) then
      @question.answer_id = params[:answer_id]
      @question.save
    end
    respond_with @question
  end
  
  private
  def auth
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end    
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :html

  def index
     @search_box = params[:search_box]
     if @search_box.empty?
       @questions = Question.find(:all)
     else
       @questions = Question.find(:all, :conditions => ["upper(title) LIKE upper(?)", "%#{@search_box}%"])
     end
     respond_with @questions, @search_box
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.erb
<h2>Questions</h2>
<div id="questions">
  <%= link_to 'Ask Question', new_question_path, :class => 'ask'  %>
  <%= render :partial => 'shared/question_list', :local => {:questions => @questions} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabOverflow</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery-ui" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="structure">
    <div id="flash">
      <% if flash[:notice] %>
        <div id="notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div id="alert"><%= flash[:alert] %></div>
      <% end %>
    </div>
    <div id="header">
      <a href="/"><h1>LabOverflow</h1></a>
    </div>
    <div id="menu">
      <%= render :partial => 'shared/user_menu' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<h2>Ask Question</h2>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, "error") %> prohibited this post from being saved:</h2>
  <ul>
  <% @question.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= form_for @question do |f|%>
  <dl>
    <dt><%= f.label :title %></dt>
    <dd>
      <%= if @question.is_edditable then @question.title else f.text_field :title end %>
    </dd>
    <dd><%= f.text_area :text %></dd>
  </dl>
  <%= f.submit :value => 'Post your Question'  %>
<% end %>

app/views/questions/edit.html.erb
<%= render :partial => 'form' %>

app/views/questions/new.html.erb
<%= render :partial => 'questions/form' %>

app/views/questions/show.html.erb
<div id="question" >
  <div class="details" data-id="<%= @question.id %>">
    <h2><%= @question.title %></h2>
    <p><%= @question.text %></p>

    <div class="question_menu">
    <% if @question.is_edditable %>
      <%= link_to 'Edit Question', edit_question_path, :class => 'edit'  %>
    <% end %>
    </div>

    <div class="owner">
      <span>asked by <%= @question.user.name%></span>
    </div>
  </div>
  
  <% if @question.answers.any? %>
  <div id="answers">
    <h3>Answers</h3>
    <% @question.answers.each do |a| %>
    <div class="answer" >
		<% if @question.is_edditable
			selected = @question.answer_id == a.id
		%>
			<%= check_box_tag 'accept', a.id, selected, :class=> "accept"%>  
      <% end %>		
      <p><%= a.text %> </p>
      <p>answered by <%= a.user.name%></p> 
    </div>
    <% end %>
  </div>
  <% end %>
  
  <div id="answer_form">
    <%= form_for [@question, @question.answers.build] do |a|%>
      <%= a.text_area :text %>
      <div class="form_buttons">
        <%= a.submit :value => 'Post your Answer' %>
      </div>
    <% end %>  
  </div>

  <%= link_to 'Back', "/" %>
</div>

app/views/search/index.html.erb
<h2>Result for: <%= @search_box %></h2>
<%= render :partial => 'shared/question_list', :local => {:questions => @questions} %>

app/views/shared/_question_list.erb
  <% @questions.each do |q| %>
  <div class="question">
    <%= link_to q.title, question_path(q) %>
    <b>by <%= q.user.name%></b>
  </div>
  <% end %>

app/views/shared/_user_menu.erb
<% if user_signed_in? %>
  <div id="user_avatar">
    <%= image_tag current_user.gravatar %>
  </div>
  <div id="user_menu">
    <span><%= current_user.name %></span>
    <ul>
      <li><%= link_to 'sign out', destroy_user_session_path %></li> | 
      <li><%= link_to 'edit profile', edit_user_registration_path %></li>
    </ul>
  </div>
<% else %>
  <%= link_to 'sign up', new_user_registration_path %> | 
  <%= link_to 'sign in', new_user_session_path %>
<% end %>